apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: analysis_skill
  version: default
  rules:
    - actions: ['view', 'manage']
      effect: EFFECT_ALLOW
      roles: ['administrator']
      condition:
        match:
          expr: request.principal.attr.enabled == true
