apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: git-code-reviewer-identity-route
  namespace: git-code-reviewer
  labels:
    app.kubernetes.io/name: git-code-reviewer
    app.kubernetes.io/component: identity
spec:
  hostnames:
    - auth.pr-review.prism.ai
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-gateway
      namespace: envoy-gateway-system
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /realms/git-code-reviewer
        - path:
            type: PathPrefix
            value: /resources
      backendRefs:
        - group: ''
          kind: Service
          name: git-code-reviewer-identity
          port: 80
          weight: 1
