apiVersion: v2
name: git-code-reviewer
description: Browser-based pull request review service for GitHub Enterprise Server
type: application
version: 0.8.2
appVersion: '0.7.0-alpha.3'
dependencies:
  - name: postgresql
    version: 18.8.14
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: keycloak
    version: 25.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: keycloak.enabled
